"""add mesures_iot table

Revision ID: 0db6ffca86dc
Revises: 0001
Create Date: 2026-07-01 11:11:56.746075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db6ffca86dc'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesures_iot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('site', sa.String(length=50), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('vibration_mms', sa.Float(), nullable=True),
    sa.Column('debit_uh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'sensor_id', name='uq_mesures_iot_timestamp_sensor')
    )
    op.create_index(op.f('ix_mesures_iot_line_id'), 'mesures_iot', ['line_id'], unique=False)
    op.create_index(op.f('ix_mesures_iot_sensor_id'), 'mesures_iot', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_mesures_iot_site'), 'mesures_iot', ['site'], unique=False)
    op.create_index(op.f('ix_mesures_iot_timestamp'), 'mesures_iot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesures_iot_timestamp'), table_name='mesures_iot')
    op.drop_index(op.f('ix_mesures_iot_site'), table_name='mesures_iot')
    op.drop_index(op.f('ix_mesures_iot_sensor_id'), table_name='mesures_iot')
    op.drop_index(op.f('ix_mesures_iot_line_id'), table_name='mesures_iot')
    op.drop_table('mesures_iot')
    # ### end Alembic commands ###
