"""add ordres_erp table

Revision ID: c0251bc5f83c
Revises: 0db6ffca86dc
Create Date: 2026-07-02 10:58:36.481970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0251bc5f83c'
down_revision: Union[str, None] = '0db6ffca86dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordres_erp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordre_id', sa.String(length=50), nullable=False),
    sa.Column('produit_ref', sa.String(length=20), nullable=False),
    sa.Column('site', sa.String(length=50), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('date_lancement', sa.DateTime(), nullable=False),
    sa.Column('date_fin_prevue', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('ouvrier_hash', sa.String(length=64), nullable=False),
    sa.Column('quantite_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produit_ref'], ['produits.produit_ref'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre_id', name='uq_ordres_erp_ordre_id')
    )
    op.create_index(op.f('ix_ordres_erp_line_id'), 'ordres_erp', ['line_id'], unique=False)
    op.create_index(op.f('ix_ordres_erp_ordre_id'), 'ordres_erp', ['ordre_id'], unique=True)
    op.create_index(op.f('ix_ordres_erp_ouvrier_hash'), 'ordres_erp', ['ouvrier_hash'], unique=False)
    op.create_index(op.f('ix_ordres_erp_produit_ref'), 'ordres_erp', ['produit_ref'], unique=False)
    op.create_index(op.f('ix_ordres_erp_site'), 'ordres_erp', ['site'], unique=False)
    op.create_index(op.f('ix_ordres_erp_statut'), 'ordres_erp', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordres_erp_statut'), table_name='ordres_erp')
    op.drop_index(op.f('ix_ordres_erp_site'), table_name='ordres_erp')
    op.drop_index(op.f('ix_ordres_erp_produit_ref'), table_name='ordres_erp')
    op.drop_index(op.f('ix_ordres_erp_ouvrier_hash'), table_name='ordres_erp')
    op.drop_index(op.f('ix_ordres_erp_ordre_id'), table_name='ordres_erp')
    op.drop_index(op.f('ix_ordres_erp_line_id'), table_name='ordres_erp')
    op.drop_table('ordres_erp')
    # ### end Alembic commands ###
